apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  annotations:
    nais.io/read-only-file-system: "false"
  name: umami-devel
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  valkey:
  - instance: sessions
    access: readwrite
  - instance: umami-devel
    access: readwrite
  - instance: lookup
    access: read
  env:
    - name: "DATABASE_TYPE"
      value: "postgresql"
    - name: "FORCE_SSL"
      value: "1"
    - name: "DISABLE_TELEMETRY"
      value: "1"
    - name: "LOG_QUERY"
      value: "0"
    - name: "SKIP_DB_MIGRATION"
      value: "0"
  accessPolicy:
    inbound:
      rules:
        - application: umami-proxy
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        databases:
          - name: umami-devel
            users:
              - name: datastream
        diskAutoresize: true
  ingresses:
    - "https://umami-devel.ansatt.nav.no"
    - "https://umami-devel.intern.nav.no"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
  liveness:
    path: "/login"
    port: 3000
  readiness:
    path: "/login"
    port: 3000
  replicas:
    cpuThresholdPercentage: 50
    max: 8
    min: 2
  port: 3000
